### ISSUE TITLE
Problem after build nuxt

### ISSUE THREAD

**Issue by hexters** [f/vue-wait#69]
I have problem `Cannot assign to read only property 'message' of object ''` after build nuxt. please fix it. thanks
<img width="1271" alt="Screenshot 2019-03-27 at 10 59 19 AM" src="https://user-images.githubusercontent.com/7827420/55049713-ec7a0880-507f-11e9-86e9-25cef30fba27.png">

**Comment by vinayakkulkarni** [comment]
```
14:34:33  FATAL  Cannot find module 'vue-wait/nuxt'
Require stack:
- /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/core/dist/core.js
- /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/cli/dist/cli-chunk.js
- /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/cli/dist/cli.js
- /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/nuxt/bin/nuxt.js

  Error: Cannot find module 'vue-wait/nuxt'
  Require stack:
  - node_modules/@nuxt/core/dist/core.js
  - node_modules/@nuxt/cli/dist/cli-chunk.js
  - node_modules/@nuxt/cli/dist/cli.js
  - node_modules/nuxt/bin/nuxt.js
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:624:31)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:164:36)
  at promise.then (node_modules/@nuxt/utils/dist/utils.js:1790:43)


   ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                              │
   │   ✖ Nuxt Fatal Error                                                                                         │
   │                                                                                                              │
   │   Error: Cannot find module 'vue-wait/nuxt'                                                                  │
   │   Require stack:                                                                                             │
   │   -                                                                                                          │
   │   /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/core/dist/core.js       │
   │   -                                                                                                          │
   │   /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/cli/dist/cli-chunk.js   │
   │   -                                                                                                          │
   │   /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/@nuxt/cli/dist/cli.js         │
   │   -                                                                                                          │
   │   /Users/vinayak/Development/Work/Hawksight/HawksightSRM-FrontEnd/node_modules/nuxt/bin/nuxt.js              │
   │                                                                                                              │
   ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
I got this while using it with Nuxt
